export class person
{
    church: string;
    name: string;
    maritalState: string;
    createdDate: Date;
    lastModified: Date;
    eId: number;
    birthDate: Date;
    placeOfBirth: string;
    baptismDate: Date;
    placeOfBaptism: string;
    edQualification: string;
    address: string;
    jobTitle: string;
    jobAddress: string;
    militaryStatus: string ;
    relatedChurch: string;
    confessoPriest:string;
    confessorChurch :string;
    confessionRate: string;
    eucharistRate: string;
    foreignCountryName: string;
    foreignCountryDate: Date;
    familyLinks : string;
    engagedBefore: number;
    marriedOutside: string;
    marriedInside: string;
    churchMarriage: number;
    marriagePlace: string;
    marriagePriest: string;
    civilMarriage : string;
    civilMarriageDate: Date;
    maritalStatus: string;
    widowhoodDate: Date;
    marriedBeforeWidowhood: number;
    marriageBeforeWidowhoodInfo: string;
    divorced: number;
    court: string;
    caseNum: number;
    caseDate: Date;
    marriageApprovalSource: string;
    marriageApprovalDate: Date;
    childsNum: number;
    childAge: string;
    childsBiptesm: string;
}